# 2.1 数据操作
## 2.1.1 入门
首先导入PyTorch

In [5]:
import torch

张量表示由一个数值组成的数组，这个数组可能有多个维度。具有一个轴的张量对应数学上的向量（vector）。具有两个轴的张量对应数学上的 矩阵（matrix）。具有两个轴以上的张量没有特殊的数学名称。

首先，可以使用arange创建一个行向量x。这个行向量包含从0开始的前12个整数，它们被默认创建为浮点数。张量中的每个值都称为张量的元素（element）。例如，张量x中有12个元素。除非额外指定，否则新的张量将存储在内存中，并采用基于CPU的计算。

In [6]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

可以通过张量的shape访问张量的形状（沿每个轴的长度）

In [8]:
x.shape

torch.Size([12])

如果只想知道张量中元素的总数，即形状的所有元素乘积，可以检查它的大小（size）。 因为这里在处理的是一个向量，所以它的 shape 与它的 size 相同。

In [9]:
x.numel()

12

In [ ]:
要改变张量的形状而不改变元素数量和元素值，可以调用 reshape 函数。 例如，可以把张量x从形状为(12, )的行向量转换为形状为(3,4)的矩阵。这个新的张量包含与转换前相同的值，但是它被看成一个3行4列的矩阵。要重点说明一下，虽然张量的形状发生了改变，但其元素值并没有变。注意，通过改变张量的形状，张量的大小不会改变。

In [10]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

虽然可以很方便的改变张量的形状，但不需要通过手动指定每个维度来改变形状。也就是说，**如果我们的目标形状是(高度,宽度) ，那么在知道宽度后，高度应当会隐式得出，我们不必自己做除法。**在上面的例子中，为了获得一个3行的矩阵，我们手动指定了它有3行和4列。幸运的是，张量在给出其他部分后可以自动计算出一个维度。**我们可以通过在希望张量自动推断的维度放置-1来调用此功能**。在上面的例子中，我们可以用x.reshape(-1,4)或x.reshape(3,-1)来取代x.reshape(3,4)。例如：

In [13]:
X1 = x.reshape(3, -1)
X1

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

有时，我们希望使用全0、全1、其他常量或者从特定分布中随机采样的数字来初始化矩阵。我们可以创建一个形状为 (2, 3, 4) 的张量，其中所有元素都设置为0。代码如下：

In [15]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

同样，我们可以创建一个形状为(2,3,4)的张量，其中所有元素都设置为1。代码如下：

In [16]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
有时想通过从某个特定的概率分布中随机采样来得到张量中每个元素的值。例如，当构造数组来作为神经网络中的参数时，通常会随机初始化参数的值。以下代码创建一个形状为 (3, 4) 的张量。其中的每个元素都从均值为0、标准差为1的标准高斯（正态）分布中随机采样。

In [17]:
torch.randn(2,4)

tensor([[ 0.3363, -0.1988, -1.9885,  0.0591],
        [-1.0646, -0.9038, -0.5442,  0.6460]])

还可以通过提供包含数值的 Python 列表（或嵌套列表）来为所需张量中的每个元素赋予确定值。在这里，最外层的列表对应于轴 0，内层的列表对应于轴 1。

In [18]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 2.1.2 运算

对于任意具有相同形状的张量，常见的标准算术运算符（+、-、*、/ 和 **）都可以被升级为按元素运算。我们可以在同一形状的任意两个张量上调用按元素操作。在下面的例子中，我们使用逗号来表示一个具有5个元素的元组，其中每个元素都是按元素操作的结果。

In [22]:
a = torch.tensor([1.0, 2, 4, 8])
b = torch.tensor([3, 4, 6, 8])
a + b, a - b, a * b, a / b, a ** b # 求幂

(tensor([ 4.,  6., 10., 16.]),
 tensor([-2., -2., -2.,  0.]),
 tensor([ 3.,  8., 24., 64.]),
 tensor([0.3333, 0.5000, 0.6667, 1.0000]),
 tensor([1.0000e+00, 1.6000e+01, 4.0960e+03, 1.6777e+07]))

还可以按元素方式应用更多的计算，包括求幂：

In [23]:
torch.exp(a)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

除此之外，还可以把多个张量 连结（concatenate） 在一起，把它们端对端地叠起来形成一个更大的张量。 我们只需要提供张量列表，并给出沿哪个轴连结。下面的例子分别演示了当我们沿行（轴-0，形状的第一个元素）和按列（轴-1，形状的第二个元素）连结两个矩阵时会发生什么情况。我们可以看到，第一个输出张量的轴-0长度 ( 6 ) 是两个输入张量轴-0长度的总和 ( 3+3 )；第二个输出张量的轴-1长度 ( 8 ) 是两个输入张量轴-1长度的总和 ( 4+4 )。

In [24]:
m = torch.arange(12, dtype=torch.float32).reshape((3,4))
n = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
m, n

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [26]:
# 沿行连接
torch.cat((m, n), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [27]:
# 沿列连接
torch.cat((m, n), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])